### ISSUE TITLE
Integrate workshop material into Library Carpentry?

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/2018-07-09-FAIR-Data-and-Software#10]
@libcce suggested we discuss how our workshop material can best be reused. First off: presentation slides are under [CC-BY 3.0 DE](https://creativecommons.org/licenses/by/3.0/de/deed.en).

Opinions are welcome :-) Please comment below.

#### Tasks that should be completed before a decision

- [x] recordings with PDF-version of the presented slides on av.tib.eu
- [x] these & other materials [hyperlinked from within the schedule](https://tibhannover.github.io/2018-07-09-FAIR-Data-and-Software/#schedule)

#### Other things to consider & related work that already started

This also affects #3 & https://github.com/swcarpentry/r-novice-inflammation/issues/309. The latter is intended for moving some material from [TIBHannover/FAIR-R](https://github.com/TIBHannover/FAIR-R) upstream.

**Comment by libcce** [comment]
@katrinleinweber the idea was to condense the content to Markdown/episodes in a FAIR Data & Software lesson. This will allow others to contribute and iteratively develop the lesson.

**Comment by mkuzak** [comment]
@libcce I like the idea. Any way to render .md slides on GitHub? :)

**Comment by katrinleinweber** [comment]
Not directly AFAIK, but definitely with [GitPitch.com](https://gitpitch.com/).

Alternatively, I'm fine with inviting people to Google Drive Folder and develop the slides there.

**Comment by mkuzak** [comment]
I'd be in favour of trying out gitpitch.com

**Comment by libcce** [comment]
If we use Google to convert the material, it potentially forces us to refine/elaborate for the lesson episodes. When I talked to Angelina, it sounded like there were 6 episodes. Google drive/docs would allow us to invite Angelina as well.

**Comment by konrad** [comment]
Couldn't that go directly go into https://github.com/LibraryCarpentry/lc-research-data?

**Comment by libcce** [comment]
@konrad yes, that repo started out with the same idea during the Mozsprint unless we want to create a new repo?

**Comment by katrinleinweber** [comment]
```
if (content-transfer needed):
    into Carpentry lesson format
then
    https://github.com/LibraryCarpentry/lc-research-data
```

My 2ct ;-)   Either way: [the editable Google Slides](https://drive.google.com/open?id=1JO-0SjKw52ICbNSHZuqdXjdIZIrh3Alp). I named the current version `presented & shared` & downloaded backups.

**Comment by libcce** [comment]
I think I'd still like to see in the LC lesson format but defer to you @katrinleinweber.

**Comment by katrinleinweber** [comment]
Please have a look at our [module-FAIR-data](https://github.com/TIBHannover/module-FAIR-data) and its source: [ReproducibleImaging.org](https://www.reproducibleimaging.org/module-FAIR-data/). How much of the episodes you are interested in does that cover?

**Comment by libcce** [comment]
I'd say TIBFDS could benefit from having an ethics episode but we can expand on the current episode in module-FAIR-data.
