### ISSUE TITLE
Add section for follow-up events / hacky hours / FAIR meet-up / study group

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/2018-07-09-FAIR-Data-and-Software#11]
Instead of setting up a different website for the weekly follow-up, we could add a new folder here & add posts to it.

Alternative templates for dedicated site:

- https://hackyhour.github.io/
- https://github.com/au-oc/
- https://github.com/mozillascience/?q=study

**Comment by lwjohnst86** [comment]
Just my two cents, but if you want more of a diverse "non-techy/nerdy" crowd, *don't* use the Hack Hour template/website... it feels more targeted to people who do programming more "seriously"/"professionally". At the UofTCoders, we used to be called "scientific coders" but eventually switched to just "coders" because people felt like the group wasn't for them... "scientific coders" to them felt like it was for computer scientists or physicists doing hardcore programming.

My advice would be to go and find people who would be your "target audience" and show them these different templates, ask their opinion on what would get them to come, etc.

**Comment by konrad** [comment]
I agree that the name and template have to be questioned. I told several people from a library environment without coding skills about the hacky hours and the were actually rather enthusiastic about it (and liked the name) I hope I can make a more systematic assessment of this but I would also consider to discuss this in the very first meeting. I would also ask if a lighter color scheme would be more inviting. I think the introduction text will be more important. Also the language is a rather tricky issue for our case. In a scientific environment English would not be a problem, but for librarians in Germany this is as far as I see less commonly used.

**Comment by katrinleinweber** [comment]
The consensus so far seems to be to use Mozilla's Study Group template. @lwjohnst86: Do you know whether it's possible to host the site based on a single repo within an existing organisation? Or does it have to be a dedicated org with several repos?

**Comment by lwjohnst86** [comment]
It can be both! The link will by default resolve to `....github.io/studyGroup`. If that answers your question.

**Comment by katrinleinweber** [comment]
Hm, so one can use the issues of `StudyGroup` as the `Events` section? A separate [Events](https://github.com/UofTCoders/Events) repo is not needed?

**Comment by lwjohnst86** [comment]
Ah, I see what you are meaning. I thought you meant for the Mozilla Study Group repo. We heavily modified the Mozilla Study Group repo to fit our purposes. I would suggest you fork the Mozilla Science Lab one. That one is self contained.

**Comment by katrinleinweber** [comment]
Your solution with issues = events is very neat, though... Can the event repo be renamed?

**Comment by lwjohnst86** [comment]
Yea, for sure. If you want the issues "events" to show up on the study group website like we have in UofTCoders, you will need to change to the new name. You can do that in the I think one of the files in `_includes/events.html` file

**Comment by katrinleinweber** [comment]
Draft website: https://github.com/katrinleinweber/FAIR-studyGroup/. To be discussed whether we should use it.

**Comment by rbirkelbach** [comment]
Hi,
just an idea: maybe it would be good to create  a github organisation in which the fair-studygroup website will have its own repo and participants can become members of this organisation?

**Comment by lwjohnst86** [comment]
I agree with this idea @rbirkelbach!

**Comment by katrinleinweber** [comment]
Generally yes, but would it be _better_ (with just one repo) than in the [org that already has the `tibfds` repos](https://github.com/TIBHannover/?q=tibfds)? We're not moving those ;-)

**Comment by lwjohnst86** [comment]
You're right, I forgot it was associated with the TIB github org. I guess it depends what you want. Do you want it an "official" initiative of TIB or do you want it be more informal and grow with people who are interested in becoming more involved... And if they did want to be involved, would you give them access to the TIBHannover org repos? Or do you want to be the "ultimate gatekeeper" of this initiative. Up to you!

**Comment by katrinleinweber** [comment]
Done in 0167d8b54602407711e22b68cee6e5f725cffb43. I'm inviting external collaborators to https://github.com/TIBHannover/FAIR-studyGroup.
