### ISSUE TITLE
Brainstorming topic ideas for follow-up events / study group

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/2018-07-09-FAIR-Data-and-Software#13]
On the first meeting the consensus seemed to be to spend the August meetings without specific topics, bringing in new people who may be interested in participating regularly and deciding on a medium to organise the events in (see #11).

After a vacation-induced break during September, we'll start with weekly topics in October. In each case, one or two volunteers prepare an introduction to the topic, and we then dig into with the group, discussing, applying it to own projects, etc.

So, this issue thread is for collecting topics ideas, even just keywords:

- RStudio tricks, `.rproj`ects
- Which other R statements besides `function()`, `for`, `return()`, etc. are there?
- Data visualisation: 
  - animations
  - interactions
- [Shiny] apps
- re3data.org curation
- improving reproducibility in projects, analyses, documents, etc. ([rrtools] & its [addin]) 
- How to organise ones browser bookmarks to improve re-findability?
- Watching a [conference recording / webinar][rec] & discussing it.
- Bring a current problem that you tried solving, present it and we try to find a solution together ([rubber-ducking]; _This may be a permanent theme of the meetings_)

[addin]: https://github.com/nevrome/rrtools.addin#rrtoolsaddin
[rrtools]: https://github.com/benmarwick/rrtools#rrtools-tools-for-writing-reproducible-research-in-r
[rubber-ducking]: https://rubberduckdebugging.com/
[Shiny]: https://shiny.rstudio.com/
[rec]: https://docs.google.com/presentation/d/1v9q7jP5TC3HxKGeGL294KBK919II_vFFHHfSceJQt9s/edit#slide=id.g3c8ac7cb36_0_0

**Comment by katrinleinweber** [comment]
@lambo suggests [Kibana](https://www.elastic.co/products/kibana), [Vitro](http://vitro.mannlib.cornell.edu/).

**Comment by rbirkelbach** [comment]
Packaging research software, dealing with dependencies etc

 - packrat
 - miniCRAN
 - conda
 - docker

Also interesting: [drake](https://github.com/ropensci/drake)

**Comment by katrinleinweber** [comment]
Suggesting people also go to the local [Python-Meetup](https://www.meetup.com/de-DE/Hannover-Python-Meetup/) & [RUG](https://www.meetup.com/de-DE/Hannover-R-User-Group/).

**Comment by david-morris** [comment]
Encouraging people to just share their code seems like a helpful tactic.  Some aspects of this:

* See if we can find any evidence of sharing code leading to citations
* Give examples of mediocre code being cited anyway

This seems like it synchronizes with encouraging people to use Git.

**Comment by katrinleinweber** [comment]
We should also encourage people to go to the local [Python-Meetup](https://www.meetup.com/de-DE/Hannover-Python-Meetup/) & [RUG](https://www.meetup.com/de-DE/Hannover-R-User-Group/).

**Comment by katrinleinweber** [comment]
- comparing GitHub & GitLab

**Comment by lambo** [comment]
Lessons learned and open issues when preparing a collaborative Gitbook: https://open-science-training-handbook.gitbook.io/book/ - This is an ongoing project; currently we're about to prepare GitHub based translation. I'd also come up with a few reflections and opinions on the difference between git-style collaboration on large text documents, versus continuous collaborative writing, like with Etherpad or Fiduswriter. (TL;DR Both have their strengths, and most probably you will have to use both methods in your large-scale open collaborative writing project. ;-) )

**Comment by david-morris** [comment]
> We should also encourage people to go to the local Python-Meetup & RUG.

We might also be interested in the [Linux Users Group](https://lug-hannover.de/wiki/index.php?Hauptseite)

**Comment by katrinleinweber** [comment]
I started moving some of my own brainstormed ideas into [the `FAIR-studyGroup` as issues ](https://github.com/tibhannover/FAIR-studyGroup/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aevent)

**Comment by katrinleinweber** [comment]
@david-morris suggests: How to deal with errors? How to read error messages? Tools to improve error messages ([backtrace](https://github.com/nir0s/backtrace) in Python), exception handling.

**Comment by Zack-83** [comment]
I would like to learn something about

* Structured objects:
  - creating new object structures;
  - creating new objects with given structure;
  - assigning a defined structure to an existing object (for instance, to convert a flat data frame in a deep, nonuniform list and viceversa);

with `R` or with a more suitable language.

* Semantic technologies:
  - creating ontologies = best practices and available software;
  - using ontologies = embedding of ontologies / vocabulary in metadata scheme;
  - design of search engines for advanced search.

**Comment by katrinleinweber** [comment]
Dear @Zack-83,

with "structured objects", do you mean stuff like https://github.com/TIBHannover/BacDiveR/issues/31? I had to figure out how to coerce an externally downloaded, nesten JSON into a  useful R-datastructure. Maybe https://www.rstudio.com/resources/videos/how-to-work-with-list-columns/ would be useful to you?

About "semantic technologies", I'm not sure... Please create further event suggestions as [issues over here](https://github.com/tibhannover/FAIR-studyGroup/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aevent). And feel free to come to [our events](https://tibhannover.github.io/FAIR-studyGroup/#portfolio).
